server:
  port: 8091
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: mynacos
        namespace: 3a0cbc15-ee32-44df-9067-8dd20e3a7608

# 开启feign的熔断机制
feign:
  hystrix:
    enabled: true