server:
  port: 18092
spring:
  application:
    name: prouducer
  cloud:
    nacos:
      discovery:
        server-addr: mynacos
        namespace: 3a0cbc15-ee32-44df-9067-8dd20e3a7608
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.16.1.39:3306/zhang
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.16.1.39:3306/test
          username: root
          password: root
  redis:
    host: 172.16.1.39
    database: 0 # Redis数据库索引（默认为0）
    port: 6380 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 172.16.1.39
    port: 5762
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完后再处理下一条
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如配2.0，第一次就等10s，第二次等20s，第三次等40s
        multiplier: 1
elasticsearch:
  host: 172.16.1.39
  port: 9200